name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [server, client]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Go test
        run: go test ./...
        working-directory: ${{ matrix.module }}

      - name: Go test (race)
        run: go test -race ./...
        working-directory: ${{ matrix.module }}
        env:
          CGO_ENABLED: 1

      - name: Go vet
        run: go vet ./...
        working-directory: ${{ matrix.module }}

      - name: Go vet
        run: go vet ./...
        working-directory: ${{ matrix.module }}
